config/routes.rb
Rails.application.routes.draw do
  resources :fiche_categories
  resources :fiche_tags
  resources :fiches
  resources :categories
  resources :tags
  
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root 'home#index'
  get 'home/index'
  get 'home/liens'
  get 'home/private'

  get 'map' => 'map#index'
  post 'map/search'
  post 'map/analyse'

  resources :demands do
    resources :instructions, shallow: true  
  end

  resources :instructions do
    resources :endsteps
  end
  
  resources :endsteps
  
  get 'mdpages/*path' => 'mdpages#show', as: :mdpages
  
# ============================================================
# ============================================================
# ============================================================


  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  # ruby bin/rails routes
  resources :articles do
    resources :comments
  end

  resources :messages
  resources :books
  resources :links
  resources :users
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud

    if user.id
      if user.demandeur?
        can :manage, Demand, user_id: user.id
      end
      if user.instructeur?
        can :read, Demand
        can :manage, Instruction, user_id: user.id
      end
      if user.valideur?
        can :read, Instruction
        can :manage, Endstep, user_id: user.id
      end
      if user.superviseur?
        can :read, :all
      end
    end
    
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
      has_many :fiche_categories
      has_many :fiches, through: :fiche_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  include Visible
  
  belongs_to :article
  belongs_to :user
  
end

app/models/demand.rb
class Demand < ApplicationRecord
  belongs_to :user
  has_one :instruction, dependent: :destroy
end

app/models/endstep.rb
class Endstep < ApplicationRecord
  belongs_to :user
  belongs_to :instruction
end

app/models/fiche.rb
class Fiche < ApplicationRecord
  
  has_many :fiche_categories
  has_many :categories, through: :fiche_categories
  has_many :fiche_tags
  has_many :tags, through: :fiche_tags

  has_one_attached :doc_pdf
  
  def pdf_url
    if self.doc_pdf.attached?
      ## https://stackoverflow.com/questions/50424251/how-can-i-get-url-of-my-attachment-stored-in-active-storage-in-my-rails-controll
      Rails.application.routes.url_helpers.rails_blob_url(
        self.doc_pdf.blob,
        only_path: true   ## Rails.application.config.action_mailer.default_url_options
      ).to_s
    else
      "https://drive.google.com/file/d/#{self.googlepdf_code}"
    end
  end

  def target_style
    if self.doc_pdf.attached?
      ""
    else
      'target="_blank"'.html_safe
    end
  end
  
end

app/models/fiche_category.rb
class FicheCategory < ApplicationRecord
  belongs_to :fiche
  belongs_to :category
end

app/models/fiche_tag.rb
class FicheTag < ApplicationRecord
  belongs_to :fiche
  belongs_to :tag
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :user
  belongs_to :demand
  has_one :endstep, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
      has_many :fiche_tags
      has_many :fiches, through: :fiche_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable

  enum role: [:demandeur, :instructeur, :valideur, :superviseur]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :demandeur
  end

  attr_accessor :login

  has_many :articles
  has_many :comments
  has_many :links
  has_many :demands
  has_many :instructions
  has_many :endsteps
  
  validates :username, presence: true, uniqueness: {case_sensitive: false},
            format: {with: /\A[a-zA-Z0-9 _\.]*\z/}

  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable


  def self.find_first_by_auth_conditions(warden_conditions)
    
    conditions =  warden_conditions.dup

    if login = conditions.delete(:login)
      where(conditions.to_hash)
        .where(
          "lower(username) = :value OR lower(email) = :value",
          value: login.downcase
        )
        .first
    else
      where(conditions.to_hash).first
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  ##http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  load_and_authorize_resource
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    # @article = Article.new(title: "...", body: "...")
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end


  
  
  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= current_user %>
  </div>

  <div>
    <%= form.submit class: "button primary" %>
    <a class="button secondary" href=<%= root_path() %>>Cancel</a> 
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>


Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <!-- <a href="<%= article_path(article) %>"> -->
        <!--   <%= article.title %> -->
        <!-- </a> -->
        <%= link_to article.title, article %>
      </li>
    <% end %> 
  <% end %>
</ul>

<footer>
<div>
  <%= link_to "New Article", new_article_path %>
  | <%= link_to "Home", root_path %>
</div>
</footer>






<!-- <form> -->
<!--   <div class="grid-container"> -->
<!--     <div class="grid-x grid-padding-x"> -->
<!--       <div class="medium-6 cell"> -->
<!--         <label>Input Label -->
<!--           <input type="text" placeholder=".medium-6.cell"> -->
<!--         </label> -->
<!--       </div> -->
<!--       <div class="medium-6 cell"> -->
<!--         <label>Input Label -->
<!--           <input type="text" placeholder=".medium-6.cell"> -->
<!--         </label> -->
<!--       </div> -->
<!--     </div> -->
<!--   </div> -->
<!-- </form> -->

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
          } %></li>
  <li><%= link_to "Articles", articles_path() %> | <%= link_to "Home", root_path() %></li>
</ul>




<h2>Comments</h2>
<%= render @article.comments %>



<h2>Add a comment:</h2>
<%= render 'comments/form' %>


  