config/routes.rb
Rails.application.routes.draw do
  resources :fiche_categories
  resources :fiche_tags
  resources :fiches
  resources :categories
  resources :tags
  
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root 'home#index'
  get 'home/index'
  get 'home/liens'
  get 'home/private'

  get 'map' => 'map#index'
  post 'map/search'
  post 'map/analyse'

  resources :demands do
    resources :instructions, shallow: true  
  end

  resources :instructions do
    resources :endsteps
  end
  
  resources :endsteps
  
  get 'mdpages/*path' => 'mdpages#show', as: :mdpages
  
# ============================================================
# ============================================================
# ============================================================


  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  # ruby bin/rails routes
  resources :articles do
    resources :comments
  end

  resources :messages
  resources :books
  resources :links
  resources :users
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud

    if user.id
      if user.demandeur?
        can :manage, Demand, user_id: user.id
      end
      if user.instructeur?
        can :read, Demand
        can :manage, Instruction, user_id: user.id
      end
      if user.valideur?
        can :read, Instruction
        can :manage, Endstep, user_id: user.id
      end
      if user.superviseur?
        can :read, :all
      end
    end
    
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
      has_many :fiche_categories
      has_many :fiches, through: :fiche_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  include Visible
  
  belongs_to :article
  belongs_to :user
  
end

app/models/demand.rb
class Demand < ApplicationRecord
  belongs_to :user
  has_one :instruction, dependent: :destroy
end

app/models/endstep.rb
class Endstep < ApplicationRecord
  belongs_to :user
  belongs_to :instruction
end

app/models/fiche.rb
class Fiche < ApplicationRecord
  
  has_many :fiche_categories
  has_many :categories, through: :fiche_categories
  has_many :fiche_tags
  has_many :tags, through: :fiche_tags

  has_one_attached :doc_pdf
  
  def pdf_url
    if self.doc_pdf.attached?
      ## https://stackoverflow.com/questions/50424251/how-can-i-get-url-of-my-attachment-stored-in-active-storage-in-my-rails-controll
      Rails.application.routes.url_helpers.rails_blob_url(
        self.doc_pdf.blob,
        only_path: true   ## Rails.application.config.action_mailer.default_url_options
      ).to_s
    else
      "https://drive.google.com/file/d/#{self.googlepdf_code}"
    end
  end

  def target_style
    if self.doc_pdf.attached?
      ""
    else
      'target="_blank"'.html_safe
    end
  end
  
end

app/models/fiche_category.rb
class FicheCategory < ApplicationRecord
  belongs_to :fiche
  belongs_to :category
end

app/models/fiche_tag.rb
class FicheTag < ApplicationRecord
  belongs_to :fiche
  belongs_to :tag
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :user
  belongs_to :demand
  has_one :endstep, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
      has_many :fiche_tags
      has_many :fiches, through: :fiche_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable

  enum role: [:demandeur, :instructeur, :valideur, :superviseur]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :demandeur
  end

  attr_accessor :login

  has_many :articles
  has_many :comments
  has_many :links
  has_many :demands
  has_many :instructions
  has_many :endsteps
  
  validates :username, presence: true, uniqueness: {case_sensitive: false},
            format: {with: /\A[a-zA-Z0-9 _\.]*\z/}

  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable


  def self.find_first_by_auth_conditions(warden_conditions)
    
    conditions =  warden_conditions.dup

    if login = conditions.delete(:login)
      where(conditions.to_hash)
        .where(
          "lower(username) = :value OR lower(email) = :value",
          value: login.downcase
        )
        .first
    else
      where(conditions.to_hash).first
    end
  end
  
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  
  before_action :set_instruction, only: %i[ show edit update destroy ]

  load_and_authorize_resource
  
  def index
    if current_user.instructeur?
      @instructions = current_user.instructions
    end  
    if current_user.valideur?
      @instructions = Instruction.left_joins(:endstep).where("instruction_id IS NULL")
    end  
    if current_user.superviseur?
      @instructions = Instruction.all
    end
  end

  
  def show
  end

  
  def new
    @demand = Demand.find(params[:demand_id])
    @instruction = Instruction.new()
  end

  # GET /instructions/1/edit
  def edit
  end

  # POST /instructions or /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)
    @instruction.user_id = current_user.id
    @instruction.save
    redirect_to instruction_path(@instruction)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instruction_params
      params.require(:instruction).permit(:soumission_reglementaire, :enjeu_biodiversite, :enjeu_patrimoine, :enjeu_ressources, :synthese, :demand_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/instructions/_form.html.erb
<%= form_with model: instruction  do |form| %>

  <div>
    <%= form.label :soumission_reglementaire, style: "display: block" %>
    <%= form.check_box :soumission_reglementaire %>
  </div>

  <div>
    <%= form.label :enjeu_biodiversite, style: "display: block" %>
    <%= form.text_area :enjeu_biodiversite %>
  </div>

  <div>
    <%= form.label :enjeu_patrimoine, style: "display: block" %>
    <%= form.text_area :enjeu_patrimoine %>
  </div>

  <div>
    <%= form.label :enjeu_ressources, style: "display: block" %>
    <%= form.text_area :enjeu_ressources %>
  </div>

  <div>
    <%= form.label :synthese, style: "display: block" %>
    <%= form.text_area :synthese %>
  </div>




  
  <div>
    <%= form.hidden_field :demand_id, :value => @demand.id %>
    <%= form.submit %>
  </div>
<% end %>

app/views/instructions/_instruction.html.erb
<h1>Demande : origine</h1>

<%= render instruction.demand %>

<h1>Instruction : suivi</h1>

<div id="<%= dom_id instruction %>">
  <p>
    <strong>Soumission reglementaire:</strong>
    <%= instruction.soumission_reglementaire %>
  </p>

  <p>
    <strong>Enjeu biodiversite:</strong>
    <%= instruction.enjeu_biodiversite %>
  </p>

  <p>
    <strong>Enjeu patrimoine:</strong>
    <%= instruction.enjeu_patrimoine %>
  </p>

  <p>
    <strong>Enjeu ressources:</strong>
    <%= instruction.enjeu_ressources %>
  </p>

  <p>
    <strong>Synthese:</strong>
    <%= instruction.synthese %>
  </p>

  <p>
    <strong>User:</strong>
    <%= instruction.user_id %>
  </p>

</div>

app/views/instructions/edit.html.erb
<h1>Editing instruction</h1>

<%= render "form", instruction: @instruction %>

<br>

<div>
  <%= link_to "Show this instruction", @instruction %> |
  <%= link_to "Back to instructions", instructions_path %>
</div>

app/views/instructions/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Instructions</h1>

<div id="instructions">
  
  

  <table>
    <% @instructions.each do |instruction| %>  
    <tr>
      <td><%= instruction.demand.id %></td>
      <td><%= instruction.demand.commune %></td>
      <td><%= instruction.demand.parcelle_section %> - <%= instruction.demand.parcelle_numero %></td>
      <td><%= instruction.soumission_reglementaire %></td>
      <td><%= instruction.synthese %></td>
      <td><a href="<%= instruction_path(instruction) %>">Voir</a></td>
    </tr>
    <% end %>
  </table>
  

</div>

<p> link_to "New instruction", new_instruction_path </p>

app/views/instructions/new.html.erb
<h1>Demande : origine</h1>

<%= render @demand %>

<h1>New instruction</h1>

<%= render "form", instruction: @instruction %>

<br>

<div>
  <%= link_to "Back to instructions", instructions_path %>
</div>

app/views/instructions/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @instruction %>

<div>
  <%= link_to "Valider cette instruction", new_instruction_endstep_path(@instruction) %> |
  <%= link_to "Back to instructions", instructions_path %>

  <%= button_to "Destroy this instruction", @instruction, method: :delete %>
</div>