config/routes.rb
Rails.application.routes.draw do
  resources :fiche_categories
  resources :fiche_tags
  resources :fiches
  resources :categories
  resources :tags
  
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root 'home#index'
  get 'home/index'
  get 'home/liens'
  get 'home/private'

  get 'map' => 'map#index'
  post 'map/search'
  post 'map/analyse'

  resources :demands do
    resources :instructions, shallow: true  
  end

  resources :instructions do
    resources :endsteps
  end
  
  resources :endsteps
  
  get 'mdpages/*path' => 'mdpages#show', as: :mdpages
  
# ============================================================
# ============================================================
# ============================================================


  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  # ruby bin/rails routes
  resources :articles do
    resources :comments
  end

  resources :messages
  resources :books
  resources :links
  resources :users
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud

    if user.id
      if user.demandeur?
        can :manage, Demand, user_id: user.id
      end
      if user.instructeur?
        can :read, Demand
        can :manage, Instruction, user_id: user.id
      end
      if user.valideur?
        can :read, Instruction
        can :manage, Endstep, user_id: user.id
      end
      if user.superviseur?
        can :read, :all
      end
    end
    
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
      has_many :fiche_categories
      has_many :fiches, through: :fiche_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  include Visible
  
  belongs_to :article
  belongs_to :user
  
end

app/models/demand.rb
class Demand < ApplicationRecord
  belongs_to :user
  has_one :instruction, dependent: :destroy
end

app/models/endstep.rb
class Endstep < ApplicationRecord
  belongs_to :user
  belongs_to :instruction
end

app/models/fiche.rb
class Fiche < ApplicationRecord
  
  has_many :fiche_categories
  has_many :categories, through: :fiche_categories
  has_many :fiche_tags
  has_many :tags, through: :fiche_tags

  has_one_attached :doc_pdf
  
  def pdf_url
    if self.doc_pdf.attached?
      ## https://stackoverflow.com/questions/50424251/how-can-i-get-url-of-my-attachment-stored-in-active-storage-in-my-rails-controll
      Rails.application.routes.url_helpers.rails_blob_url(
        self.doc_pdf.blob,
        only_path: true   ## Rails.application.config.action_mailer.default_url_options
      ).to_s
    else
      "https://drive.google.com/file/d/#{self.googlepdf_code}"
    end
  end

  def target_style
    if self.doc_pdf.attached?
      ""
    else
      'target="_blank"'.html_safe
    end
  end
  
end

app/models/fiche_category.rb
class FicheCategory < ApplicationRecord
  belongs_to :fiche
  belongs_to :category
end

app/models/fiche_tag.rb
class FicheTag < ApplicationRecord
  belongs_to :fiche
  belongs_to :tag
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :user
  belongs_to :demand
  has_one :endstep, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
      has_many :fiche_tags
      has_many :fiches, through: :fiche_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable

  enum role: [:demandeur, :instructeur, :valideur, :superviseur]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :demandeur
  end

  attr_accessor :login

  has_many :articles
  has_many :comments
  has_many :links
  has_many :demands
  has_many :instructions
  has_many :endsteps
  
  validates :username, presence: true, uniqueness: {case_sensitive: false},
            format: {with: /\A[a-zA-Z0-9 _\.]*\z/}

  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable


  def self.find_first_by_auth_conditions(warden_conditions)
    
    conditions =  warden_conditions.dup

    if login = conditions.delete(:login)
      where(conditions.to_hash)
        .where(
          "lower(username) = :value OR lower(email) = :value",
          value: login.downcase
        )
        .first
    else
      where(conditions.to_hash).first
    end
  end
  
end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  before_action :set_demand, only: %i[ show edit update destroy ]

  load_and_authorize_resource
  
  # GET /demands or /demands.json
  def index
    if current_user.demandeur?
      @demands = current_user.demands
    end
    if current_user.instructeur?
      @demands = Demand.left_outer_joins(:instruction).where("demand_id IS NULL")
    end
    if current_user.superviseur?
      @demands = Demand.all
    end
  end
 
  
  # GET /demands/1 or /demands/1.json
  def show
    
  end

  # GET /demands/new
  def new
    @demand = Demand.new
  end

  # GET /demands/1/edit
  def edit
  end

  # POST /demands or /demands.json
  def create
    @demand = Demand.new(demand_params)
    @demand.user_id = current_user.id
    respond_to do |format|
      if @demand.save
        format.html { redirect_to demand_url(@demand), notice: "Demand was successfully created." }
        format.json { render :show, status: :created, location: @demand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demands/1 or /demands/1.json
  def update
    respond_to do |format|
      if @demand.update(demand_params)
        format.html { redirect_to demand_url(@demand), notice: "Demand was successfully updated." }
        format.json { render :show, status: :ok, location: @demand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1 or /demands/1.json
  def destroy
    @demand.destroy

    respond_to do |format|
      format.html { redirect_to demands_url, notice: "Demand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demand
      @demand = Demand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def demand_params
      params.require(:demand).permit(:nom, :prenom, :mail, :commune, :parcelle_section, :parcelle_numero)
    end
    
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/demands/_demand.html.erb
<div id="<%= dom_id demand %>">
  <p>
    <strong>Nom:</strong>
    <%= demand.nom %>
  </p>

  <p>
    <strong>Prenom:</strong>
    <%= demand.prenom %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= demand.mail %>
  </p>

  <p>
    <strong>Commune:</strong>
    <%= demand.commune %>
  </p>

  <p>
    <strong>Parcelle section:</strong>
    <%= demand.parcelle_section %>
  </p>

  <p>
    <strong>Parcelle numero:</strong>
    <%= demand.parcelle_numero %>
  </p>

  <p>
    <strong>User:</strong>
    <%= demand.user_id %>
  </p>

  <div style="background-color:chartreuse;">
    <p>
      <strong>Instruction:</strong>
      <% if demand.instruction %>
        <% if demand.instruction.endstep %>
          <% if demand.instruction.endstep.validation %>
	   La décision explicite et validée.
          <% else %>
	   La validation est en attente.
          <% end %>
        <% else %>
	 L'instruction est en cours
        <% end %>
      <% else %>
         L'instruction en attente.
      <% end %>
    </p>
  </div>
  
</div>

app/views/demands/_form.html.erb
<%= form_with(model: demand) do |form| %>
  <% if demand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(demand.errors.count, "error") %> prohibited this demand from being saved:</h2>

      <ul>
        <% demand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom , :value => current_user.username%>
  </div>

  <div>
    <%= form.label :prenom, style: "display: block" %>
    <%= form.text_field :prenom %>
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_field :mail, :value => current_user.email %>
  </div>

  <div>
    <%= form.label :commune, style: "display: block" %>
    <%= form.text_field :commune %>
  </div>

  <div>
    <%= form.label :parcelle_section, style: "display: block" %>
    <%= form.text_field :parcelle_section %>
  </div>

  <div>
    <%= form.label :parcelle_numero, style: "display: block" %>
    <%= form.number_field :parcelle_numero %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/demands/edit.html.erb
<h1>Editing demand</h1>

<%= render "form", demand: @demand %>

<br>

<div>
  <%= link_to "Show this demand", @demand %> |
  <%= link_to "Back to demands", demands_path %>
</div>

app/views/demands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Demands</h1>

<div id="demands">
  <table>
    <% @demands.each do |demand| %>
    <tr>
      <td>
	<%= demand.id %>
      <td>
      <td>
	<%= demand.commune %>
      <td>
      <td>
	<%= demand.parcelle_section %> - <%= demand.parcelle_numero %>
      <td>
      <td>
	      <% if demand.instruction %>
        <% if demand.instruction.endstep %>
          <% if demand.instruction.endstep.validation %>
	   La décision explicite et validée.
          <% else %>
	   La validation est en attente.
          <% end %>
        <% else %>
	 L'instruction est en cours
        <% end %>
      <% else %>
         L'instruction non affectée.
      <% end %>
	</td>
      <td>
	<%= link_to "Show this demand", demand %>
      </td>
      
    </tr>
    <% end %>
  </table>
</div>

<%= link_to "New demand", new_demand_path %>

app/views/demands/new.html.erb
<h1>New demand</h1>

<%= render "form", demand: @demand %>

<br>

<div>
  <%= link_to "Back to demands", demands_path %>
</div>

app/views/demands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @demand %>

<div>
  <%= link_to "Instruire cette demande", new_demand_instruction_path(@demand) %> |
  <%= link_to "Back to demands", demands_path %>

  <%= button_to "Destroy this demand", @demand, method: :delete %>
</div>