config/routes.rb
Rails.application.routes.draw do
  resources :fiche_categories
  resources :fiche_tags
  resources :fiches
  resources :categories
  resources :tags
  
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root 'home#index'
  get 'home/index'
  get 'home/liens'
  get 'home/private'

  get 'map' => 'map#index'
  post 'map/search'
  post 'map/analyse'

  resources :demands do
    resources :instructions, shallow: true  
  end

  resources :instructions do
    resources :endsteps
  end
  
  resources :endsteps
  
  get 'mdpages/*path' => 'mdpages#show', as: :mdpages
  
# ============================================================
# ============================================================
# ============================================================


  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  # ruby bin/rails routes
  resources :articles do
    resources :comments
  end

  resources :messages
  resources :books
  resources :links
  resources :users
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud

    if user.id
      if user.demandeur?
        can :manage, Demand, user_id: user.id
      end
      if user.instructeur?
        can :read, Demand
        can :manage, Instruction, user_id: user.id
      end
      if user.valideur?
        can :read, Instruction
        can :manage, Endstep, user_id: user.id
      end
      if user.superviseur?
        can :read, :all
      end
    end
    
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
      has_many :fiche_categories
      has_many :fiches, through: :fiche_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  include Visible
  
  belongs_to :article
  belongs_to :user
  
end

app/models/demand.rb
class Demand < ApplicationRecord
  belongs_to :user
  has_one :instruction, dependent: :destroy
end

app/models/endstep.rb
class Endstep < ApplicationRecord
  belongs_to :user
  belongs_to :instruction
end

app/models/fiche.rb
class Fiche < ApplicationRecord
  
  has_many :fiche_categories
  has_many :categories, through: :fiche_categories
  has_many :fiche_tags
  has_many :tags, through: :fiche_tags

  has_one_attached :doc_pdf
  
  def pdf_url
    if self.doc_pdf.attached?
      ## https://stackoverflow.com/questions/50424251/how-can-i-get-url-of-my-attachment-stored-in-active-storage-in-my-rails-controll
      Rails.application.routes.url_helpers.rails_blob_url(
        self.doc_pdf.blob,
        only_path: true   ## Rails.application.config.action_mailer.default_url_options
      ).to_s
    else
      "https://drive.google.com/file/d/#{self.googlepdf_code}"
    end
  end

  def target_style
    if self.doc_pdf.attached?
      ""
    else
      'target="_blank"'.html_safe
    end
  end
  
end

app/models/fiche_category.rb
class FicheCategory < ApplicationRecord
  belongs_to :fiche
  belongs_to :category
end

app/models/fiche_tag.rb
class FicheTag < ApplicationRecord
  belongs_to :fiche
  belongs_to :tag
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :user
  belongs_to :demand
  has_one :endstep, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
      has_many :fiche_tags
      has_many :fiches, through: :fiche_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable

  enum role: [:demandeur, :instructeur, :valideur, :superviseur]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :demandeur
  end

  attr_accessor :login

  has_many :articles
  has_many :comments
  has_many :links
  has_many :demands
  has_many :instructions
  has_many :endsteps
  
  validates :username, presence: true, uniqueness: {case_sensitive: false},
            format: {with: /\A[a-zA-Z0-9 _\.]*\z/}

  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable


  def self.find_first_by_auth_conditions(warden_conditions)
    
    conditions =  warden_conditions.dup

    if login = conditions.delete(:login)
      where(conditions.to_hash)
        .where(
          "lower(username) = :value OR lower(email) = :value",
          value: login.downcase
        )
        .first
    else
      where(conditions.to_hash).first
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def liens
  end
  
  def private
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/home/index.html.erb
<div class="fr-grid-row fr-grid-row--gutters">
  
  <div class="fr-col-12">

    <p class="fr-pt-md-14v"></p> 
    <p>Application exploratoire.</p>


    
    <div data-controller="carousel" style="background-color:silver;">

      <!-- Conteneur principal pour le carrousel -->
      <div class="carousel-container">
	
	<!-- Élément carrousel -->
	<div class="carousel">
          <!-- Conteneur interne pour les diapositives -->
          <div class="carousel-inner">
            <!-- Première diapositive -->
            <div class="slide">
              <!-- Image de la première diapositive -->
	      <%= image_tag "carousel/template-evalpro-1.png" %>
            </div>
            <!-- Deuxième diapositive -->
            <div class="slide">
              <!-- Image de la deuxième diapositive -->
	      <%= image_tag "carousel/template-evalpro-2.png" %>
            </div>
            <!-- Troisième diapositive -->
            <div class="slide">
              <!-- Image de la troisième diapositive -->
	      <%= image_tag "carousel/template-evalpro-3.png" %>
            </div>
            <!-- Quatrième diapositive -->
            <div class="slide">
	      <%= image_tag "carousel/template-evalpro-4.png" %>
            </div>
            <!-- Quatrième diapositive -->
            <div class="slide">

            </div>
          </div>
	</div>
	
	<!-- Conteneur pour les boutons de navigation -->
	<div class="carousel-controls">
          <!-- Bouton pour passer à la diapositive précédente -->
          <button id="prev"><span class="fr-icon-arrow-left-s-fill fr-icon--lg" aria-hidden="true"></span></button>
          <!-- Bouton pour passer à la diapositive suivante -->
          <button id="next"><span class="fr-icon-arrow-right-s-fill fr-icon--lg" aria-hidden="true"></span></button>
	</div>

      </div> <!-- fin carousel -->

      <!-- Conteneur pour les points de navigation -->
      <div class="carousel-dots"></div>
    </div>
    
    <p class="fr-pt-md-14v"></p> 
    <p>Accéder à l'interrogation des parcelles <%= link_to "choisir la parcelle", map_path %></p>
    <p class="fr-pt-md-14v"></p> 
    
    <% if user_signed_in? %>
    <% if current_user.demandeur? %>
    <div style="background-color:pink;">
      <ul>
        <li><%= link_to "Liste des demandes ...", demands_path %></li>
        <li><%= link_to "Créer une nouvelle demande ...", new_demand_path %></li>
      </ul>
    </div>
    <% end %>
    <% if current_user.instructeur? %>
    <div style="background-color:#BDBED3;">
      <ul>
        <li><%= link_to "Liste des demandes sans instruction ...", demands_path  %></li>
        <li><%= link_to "Liste de mes instructions ...", instructions_path  %></li>  
      </ul>
    </div>
    <% end %>
    <% if current_user.valideur?%>
    <div style="background-color:#CDCEE9;">
      <ul>
        <li><%= link_to "Liste des instructions non assignées...", instructions_path  %></li>
        <li><%= link_to "Ma liste de validations ...", endsteps_path  %></li>  
      </ul>
    </div>
    <% end %>
    <% if current_user.superviseur?%>
    <div style="background-color:#DAC2AA;">
      <ul>
        <li><%= link_to "Liste des demandes...", demands_path  %></li>
        <li><%= link_to "Liste des instructions...", instructions_path  %></li>
        <li><%= link_to "Liste des validations ...", endsteps_path  %></li>  
      </ul>
    </div>
    <% end %>          
    <% end %>
    
    
  </div>

</div>

app/views/home/liens.html.erb
<ul>
  <li>
    <a href="">

    </a>
  </li>
  <li>
    <a href="https://nokogiri.org/">
      https://nokogiri.org/
    </a>
  </li>
  <li>
    <a href="https://duckduckgo.com/?t=ftsa&q=ruby+interface&atb=v355-1&ia=web">
      https://duckduckgo.com/?t=ftsa&q=ruby+interface&atb=v355-1&ia=web
    </a>
  </li>
  <li>
    <a href="https://morningcoffee.io/interfaces-in-ruby.html">
      https://morningcoffee.io/interfaces-in-ruby.html
    </a>
  </li>
  <li>
    <a href="">

    </a>
  </li>
  <li>
    <a href="">

    </a>
  </li>
  <li>
    <a href="">

    </a>
  </li>
</ul>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>